[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/events"
  to = "/.netlify/functions/events"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
